namespace Marventa.Framework.Core.Models.FileMetadata;

/// <summary>
/// Source of tags
/// </summary>
public enum TagSource
{
    User,
    AI,
    System,
    Import,
    Extracted
}

/// <summary>
/// File access levels
/// </summary>
public enum FileAccessLevel
{
    Public,
    Internal,
    Confidential,
    Restricted,
    Private
}

/// <summary>
/// Storage classes
/// </summary>
public enum StorageClass
{
    Standard,
    InfrequentAccess,
    Archive,
    DeepArchive,
    Intelligent
}

/// <summary>
/// Replica status
/// </summary>
public enum ReplicaStatus
{
    Syncing,
    Synced,
    Failed,
    Outdated
}

/// <summary>
/// Processing types
/// </summary>
public enum ProcessingType
{
    Upload,
    Conversion,
    Optimization,
    Analysis,
    Backup,
    Migration,
    Validation
}

/// <summary>
/// Processing status
/// </summary>
public enum ProcessingStatus
{
    Pending,
    Running,
    Completed,
    Failed,
    Cancelled
}

/// <summary>
/// File access types
/// </summary>
public enum FileAccessType
{
    View,
    Download,
    Edit,
    Delete,
    Share,
    Copy,
    Move,
    Preview
}

/// <summary>
/// Version types
/// </summary>
public enum VersionType
{
    Major,
    Minor,
    Patch,
    Branch,
    Fork
}

/// <summary>
/// Workflow status
/// </summary>
public enum WorkflowStatus
{
    Draft,
    Submitted,
    InReview,
    Approved,
    Rejected,
    Published,
    Archived
}

/// <summary>
/// Approval status
/// </summary>
public enum ApprovalStatus
{
    Pending,
    Approved,
    Rejected,
    Conditional
}

/// <summary>
/// Archival status
/// </summary>
public enum ArchivalStatus
{
    Active,
    Archived,
    Deleted,
    Expired,
    OnHold
}

/// <summary>
/// Backup types
/// </summary>
public enum BackupType
{
    Full,
    Incremental,
    Differential,
    Snapshot
}

/// <summary>
/// Backup status
/// </summary>
public enum BackupStatus
{
    Pending,
    InProgress,
    Completed,
    Failed,
    Expired
}

/// <summary>
/// Retention actions
/// </summary>
public enum RetentionAction
{
    Keep,
    Archive,
    Delete,
    Review
}

/// <summary>
/// Search sort orders
/// </summary>
public enum SearchSortOrder
{
    Relevance,
    CreatedAscending,
    CreatedDescending,
    ModifiedAscending,
    ModifiedDescending,
    SizeAscending,
    SizeDescending,
    NameAscending,
    NameDescending
}

/// <summary>
/// Similarity types
/// </summary>
public enum SimilarityType
{
    Visual,
    Content,
    Metadata,
    Tags,
    Usage
}

/// <summary>
/// Tag trends
/// </summary>
public enum TagTrend
{
    Rising,
    Stable,
    Declining,
    New,
    Seasonal
}

/// <summary>
/// Metadata merge modes
/// </summary>
public enum MetadataMergeMode
{
    Replace,
    Merge,
    Append,
    KeepExisting
}

/// <summary>
/// Tag suggestion sources
/// </summary>
public enum TagSuggestionSource
{
    ContentAnalysis,
    SimilarFiles,
    UserHistory,
    PopularTags,
    AutoGenerated
}